Fix crash if man is not installed when hit '?' and 'm'.
On some systems (e.g. archlinuxarm) man is not installed by default, hit
'?' and 'm' will cause ranger crashed, showing:
AttributeError: 'NoneType' object has no attribute 'poll'.